[package]
name = "crawler"
version = "0.1.0"
authors = ["Matias Fontanini <matias.fontanini@gmail.com>"]

[dependencies]
regex = "1"
http = "0.1"
url = "1.7"
lazy_static = "1.0"
reqwest = "0.8"
log = "0.4"
simple_logger = "0.5"
chan-signal = "0.3"
chan = "0.1"
